[keyboard]
bindings = [
    {key = "PageUp", action = "ScrollLineUp"},
    {key = "PageDown", action = "ScrollLineDown"}
]

[window]
title = "VENOM - Terminal"
dynamic_title = true
startup_mode = "Maximized"

